image:
  repository: otel/demo

  tag: latest-checkout

env:
  - name: OTEL_SERVICE_NAME
    value: checkout

  - name: CHECKOUT_SERVICE_ADDR
    value: "checkout:5050"

  - name: CART_SERVICE_ADDR
    value: "cart:8080"

  - name: CURRENCY_SERVICE_ADDR
    value: "currency:7000"

  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalog:3550"

  - name: PAYMENT_SERVICE_ADDR
    value: "payment:50051"

  - name: SHIPPING_SERVICE_ADDR
    value: "shipping:50051"

  - name: EMAIL_SERVICE_ADDR
    value: "email:5000"


nodeSelector: {}
tolerations: []

