{{ include "microservice.deployment" . }}
---
{{ include "microservice.service" . }}
---
{{ include "microservice.hpa" . }}
---
{{ include "microservice.ingress" . }}
---
{{ include "microservice.pdb" . }}